# -*- coding: utf-8 -*-
"""irrigation_logic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FkorpwZOdbR7pexxoMG7xhnTenkGTaNF
"""

def irrigation_advice(temp, humidity, rainfall, crop=None):
    if rainfall > 20:
        return "🌧️ Heavy rainfall detected. No irrigation needed today."
    elif rainfall > 5:
        return "🌦️ Light rain today. Reduce irrigation to 5–10 L/sq.m."
    elif temp > 32 and humidity < 40:
        return "🔥 High temperature and low humidity. Apply 25 L/sq.m."
    elif 25 <= temp <= 32:
        return "☀️ Moderate temperature. Apply 15–20 L/sq.m."
    elif temp < 25:
        return "❄️ Cool weather. Light irrigation of 10 L/sq.m is enough."
    else:
        return "🔎 Not enough information to determine irrigation needs."